Jiny song/dataform
badal-io/gcp-airflow-foundations pull request #74
Opened 2022-03-30 05:22 UTC by jinysong

updated Dataform sensor, hook, and operator
cleaned up dag examples

2022-03-30 12:50 UTC, eugenemiretsky requested changes

2022-03-30 12:50 UTC, eugenemiretsky commented on gcp_airflow_foundations/operators/api/hooks/dataform_hook.py
>      Once a run is created, it will use ApiService_RunGet to return information about the run every 10 seconds until the status is no longer RUNNING.
Is this true? I thought the operator does that, not the hook

2022-04-08 16:15 UTC, MichailParaskevopoulos approved these changes

2022-04-11 13:33 UTC, danielkulikov approved these changes

2022-04-13 20:02 UTC, eugenemiretsky approved these changes

2022-04-13 20:18 UTC, merged