Feature/column adding
badal-io/gcp-airflow-foundations pull request #75
Opened 2022-03-30 13:38 UTC by danielkulikov

Added support for new column additions to ODS/HDS. No restrictions are placed on the function itself to create the column, so it's up to the user's discretion if they need to e.g. hardcode some internal column names into it.

2022-03-30 13:48 UTC, eugenemiretsky requested changes
what is the type pf column_adding? 
A dictionary of "col_name" -> sql_function? 

Can we make it more explicit?
1) Document it
2) Maybe give it a more concrete type so it can get validated during config validation?

2022-03-30 13:48 UTC, eugenemiretsky commented on gcp_airflow_foundations/operators/gcp/hds/hds_merge_table_operator.py
> +    :param column_adding: Columna dding
missing an a

2022-03-30 17:26 UTC, danielkulikov commented
> what is the type pf column_adding? A dictionary of "col_name" -> sql_function?
> 
> Can we make it more explicit?
> 
> 1. Document it
> 2. Maybe give it a more concrete type so it can get validated during config validation?

I was going by how the column_casting was added - and it has some validation for it, but not for the actual types/dictionary keys expected. It should be:
      {"function": "SQL_FUNCTION", "output_type": BigQuery datatype}

I think we can just add explicit validation for both the casting and adding to make sure the dict is in the right form...what do you think? Creating configs for them will make configuration files extremely long and messy (esp w/ current use-cases)

2022-04-08 14:09 UTC, eugenemiretsky commented
another random thought: 
Should we call it "new_colum_udfs"(user defined functions). Seems more appropriate

2022-04-08 16:16 UTC, MichailParaskevopoulos approved these changes

2022-04-11 19:42 UTC, eugenemiretsky approved these changes

2022-04-11 21:39 UTC, merged